### ISSUE TITLE
Provide a new `npm/bump` pipeline

### ISSUE THREAD

**Issue by wojciechka** [chainguard-dev/melange#1626] opened 2024-11-08 13:22 UTC
Similar to `go/bump`, allowing one or more packages to be bumped to a newer version, assuming the specified version is newer than one in package.json.

For example:

```
  - npm/bump
    with:
      deps: express@^4.21.1
```

**Comment by luhring** [comment] 2024-11-08 13:55
I think this is a duplicate of https://github.com/chainguard-dev/melange/issues/1625... if so let's move the discussion to that issue!

If I've gotten this wrong, let's re-open this.

**Closed by luhring** 2024-11-08 13:55 UTC
Labels: duplicate

**Comment by wojciechka** [comment] 2024-11-12 11:13
This is different from #1625, but I think it should stay closed anyway.

There was a discussion on slack and bumping npm modules is not as simple as with go modules, and perhaps it has to be done in a manual way. Thread on Slack:

https://chainguard-dev.slack.com/archives/C0636FTRFED/p1729090021374439
